# Generated by Django 3.1.4 on 2021-12-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='Your Name', max_length=60),
            preserve_default=False,
        ),
    ]
